# DEBUG LEVELS: 0 - none, 1 - Error, 2 - Warning, 3 - Info
#               4 - Debug, 5 - Verbose,
#               6-ALL (extra verbose for those repeated events)
# If DEBUG_LEVEL is commented, Android's logging levels will be used
DEBUG_LEVEL = 3
